project_name: BMAI
project_homepage: https://github.com/pappde/bmai
license: MIT
copyright: 2001 Denis Papp
spdx_excluded:  # List of files or directories to exclude from REUSE compliance checks
  - .clang-format
  - .gitignore
  - .git/*
  - .github/*
  - web/*
  - CMakeLists.txt
