# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
# SPDX-License-Identifier: CC0-1.0
#
name: REUSE Compliance Check

on:
  push:
    branches: [rust]
  pull_request:
    branches: [rust]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v6
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6
